name: qr_scanner
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.1
  google_maps_flutter: ^2.1.2
  path_provider: ^2.0.9
  provider: ^6.0.2
  qr_code_scanner: ^0.7.0
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2
  url_launcher: ^6.0.20
  another_flushbar: ^1.10.28

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/preview.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "
  image: assets/preview.png
  color_dark: "
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
